##################################################################################################
# Name: Test bash looping
# Descripton: GitHub Action Workflow used to test looping in a bash file.
##################################################################################################
on:
  push:
    branches:
      - master
    paths:
    - 'deployment/arm/signalr-loop-tutorial.sh'
    - '.github/workflows/signalr-loop-tutorial.yml'
  
name: 'Test bash looping'

jobs:
  execute-bash-file:
    name: 'Execute bash file'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@master
      with:
        ref: refs/heads/master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}          

    - name: 'Create Azure Resources'
      run: |
        chmod +x ./deployment/arm/signalr-loop-tutorial.sh
        bash ./deployment/arm/signalr-loop-tutorial.sh -o oncepiece

    - name: 'Logout via Azure CLI'
      run: |
        az logout